package lambethd.kraken.data.repository.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lambethd.kraken.data.repository.converter.LocalDateTimeConverter;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Job")
public class JobDto {
    private String id;
    private String status;
    private int runeDay;
    private String jobType;
    private int progress;
    private String username;
    private LocalDateTime startTime;
    private LocalDateTime finishTime;
    private String parameters;
    private String error;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getJobType() {
        return jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public int getRuneDay() {
        return runeDay;
    }

    public void setRuneDay(int runeDay) {
        this.runeDay = runeDay;
    }

    @DynamoDBAttribute
    public int getProgress() {
        return progress;
    }

    public void setProgress(int progress) {
        this.progress = progress;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(LocalDateTime finishTime) {
        this.finishTime = finishTime;
    }

    @DynamoDBAttribute
    public String getParameters() {
        return parameters;
    }

    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    @DynamoDBAttribute
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }
}
